### ISSUE TITLE
recurring expense adds an automatic end date

### ISSUE THREAD

**Issue by YukioRivera** [YukioRivera/expenseTracker#11]
when user creates a recurring expense  then an end date, of what looks like the end of the year, gets forced on the entry

**Comment by YukioRivera** [comment]
i think this issue is related to this error
 
 web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
web_1  |     return self.wsgi_app(environ, start_response)
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
web_1  |     response = self.handle_exception(e)
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
web_1  |     reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
web_1  |     response = self.full_dispatch_request()
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
web_1  |     rv = self.handle_user_exception(e)
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
web_1  |     reraise(exc_type, exc_value, tb)
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
web_1  |     raise value
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
web_1  |     rv = self.dispatch_request()
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
web_1  |     return self.view_functions[rule.endpoint](**req.view_args)
web_1  |   File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
web_1  |     return func(*args, **kwargs)
web_1  |   File "/home/dev/expenseTracker/app/routes.py", line 311, in update_recurring_entries
web_1  |     recurring_charge.end_date = datetime.strptime(entry['endDate'], '%Y-%m-%d') if entry['endDate'] != 'N/A' else None
web_1  |   File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
web_1  |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
web_1  |   File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
web_1  |     raise ValueError("time data %r does not match format %r" %
web_1  | ValueError: time data '' does not match format '%Y-%m-%d'

**Comment by YukioRivera** [comment]
end dates are no longer bbeing added automatically but now there is a outcome of entries getting automatically added when an end date is selected. it will add all fucture entries. keep or not? I'll make a separate issue and just keep it in mind
